"""add table families

Revision ID: 0b29f7d50f6c
Revises: 84778db536f1
Create Date: 2026-07-18 13:24:29.766778

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b29f7d50f6c"
down_revision = "84778db536f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "families",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("branch_number", sa.Integer(), nullable=True),
        sa.Column("ancestral_house_address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("family_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, "families", ["family_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("family_id")

    op.drop_table("families")
    # ### end Alembic commands ###
