"""add column sibling_index

Revision ID: 2b36faeeb9a0
Revises: 95db71c17879
Create Date: 2026-07-21 14:42:26.849629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b36faeeb9a0'
down_revision = '95db71c17879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sibling_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('sibling_index')

    # ### end Alembic commands ###
