"""add column address for person

Revision ID: 73d0a1c5ec10
Revises: c8e23c09b426
Create Date: 2026-07-19 04:49:02.184216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d0a1c5ec10'
down_revision = 'c8e23c09b426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hometown', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('current_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('current_address')
        batch_op.drop_column('hometown')

    # ### end Alembic commands ###
