"""add relationship table

Revision ID: 818255453815
Revises: 339d4da7fb59
Create Date: 2026-07-18 08:48:22.444358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818255453815'
down_revision = '339d4da7fb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('related_person_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))
        batch_op.drop_constraint(batch_op.f('persons_parent_id_fkey'), type_='foreignkey')
        batch_op.drop_column('full_name')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('persons_parent_id_fkey'), 'persons', ['parent_id'], ['id'])
        batch_op.drop_column('gender')
        batch_op.drop_column('avatar')
        batch_op.drop_column('birthday')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('relationships')
    # ### end Alembic commands ###
