"""initial uuid schema

Revision ID: 84778db536f1
Revises:
Create Date: 2026-07-18 10:18:11.457573

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84778db536f1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("birthday", sa.String(length=20), nullable=True),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("related_person_id", sa.String(), nullable=False),
        sa.Column("relation_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relationships")
    op.drop_table("persons")
    # ### end Alembic commands ###
