"""add column for person table

Revision ID: 95db71c17879
Revises: fc670ce9715a
Create Date: 2026-07-21 14:27:59.764628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95db71c17879'
down_revision = 'fc670ce9715a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
