"""split birthday/death_date into day/month/year + is_lunar fields

Revision ID: 97081ac39dea
Revises: 2b36faeeb9a0
Create Date: 2026-07-26 10:45:01.047238

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97081ac39dea"
down_revision = "2b36faeeb9a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("birth_day", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("birth_month", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("birth_year", sa.SmallInteger(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "birth_is_lunar", sa.Boolean(), server_default="false", nullable=False
            )
        )
        batch_op.add_column(sa.Column("death_day", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("death_month", sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column("death_year", sa.SmallInteger(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "death_is_lunar", sa.Boolean(), server_default="false", nullable=False
            )
        )
        batch_op.drop_column("birthday")
        batch_op.drop_column("death_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("death_date", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("death_is_lunar")
        batch_op.drop_column("death_year")
        batch_op.drop_column("death_month")
        batch_op.drop_column("death_day")
        batch_op.drop_column("birth_is_lunar")
        batch_op.drop_column("birth_year")
        batch_op.drop_column("birth_month")
        batch_op.drop_column("birth_day")

    # ### end Alembic commands ###
